version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/backend"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend-html"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
