# This is a basic workflow to help you get started with Actions

name: Build Architect

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  YARN_CACHE_FOLDER : $(GITHUB_WORKSPACE)/.yarn # location of yarn cache
  BRANCH : master # branch to be used
  VERSION_NUMBER : 2021.2.0.$(GITHUB_RUN_ID) # version number of the build
  PRODUCT_NUMBER : 21.2.0.$(GITHUB_RUN_ID) # product number to be used in the installation file
  TAG : 2021.2-beta.2 # tag to be used
  TAG_LATEST : master-latest # tag to be used
  TAG_PREVIOUS: 2021.2-beta.1 # tag to compare changelog to
  IS_PRERELASE: true
  PRODUCT_VERSION: 2021.2 # used in setup to differentiate the version of architect
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup-MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      
      - uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: nuget-2021-04-11-01-${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} #hash of project files
          restore-keys: |
            nuget-2021-04-11-01-${{ runner.os }}-nuget-
        
      - name: Restore Nuget
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
              cd backend
              nuget restore Origam.sln
        
      - name: Build Architect
        run: msbuild backend/Origam.sln -m /p:Configutation="Release Architect" /p:Platform="Any CPU" 

