name: "Architect NUnit Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master, 20* ]

jobs:
  analyze:
    name: Analyze
    runs-on: windows-2022
    permissions:
      id-token: write
      contents: read
      checks: write

    strategy:
      fail-fast: false
      matrix:
        language: ['csharp']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Architect
      run: |
       msbuild backend/Origam.sln -t:restore /p:Configuration="Release Architect"
       msbuild backend/Origam.sln /p:Configuration="Release Architect"

    - name: Run NUnit Tests
      run: dotnet test --logger "trx;logfilename=test-results.trx" backend/**Tests/bin/Release/*Tests.dll
      
    - name: Produce NUnit Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: NUnit Results
        path: TestResults/test-results.trx
        reporter: dotnet-trx
