name: Frontend Build

on:
  push:
    branches: [ master, 20* ]
  pull_request:
    branches: [ master, 20* ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
            cd frontend-html
            yarn install --frozen-lockfile
            yarn build
